import "@/styles/globals.css"
import { MoralisProvider } from "react-moralis"
import { Notification, NotificationProvider } from "web3uikit"
import Header from "../components/Header"
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client"
import Head from "next/head"

const client = new ApolloClient({
    cache: new InMemoryCache(),
    uri: `https://api.studio.thegraph.com/query/43153/tasknft-marketplace/v0.0.3`,
})

export default function App({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>NFT Marketplace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <ApolloProvider client={client}>
                    <NotificationProvider>
                        <Header />
                        <Component {...pageProps} />
                    </NotificationProvider>
                </ApolloProvider>
            </MoralisProvider>
        </div>
    )
}
